spring:
  application:
    name: procredito-backend

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/procredito}
    username: ${DB_USERNAME:procredito}
    password: ${DB_PASSWORD:procredito123}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: julio.castillo.ita@gmail.com
    password: mchjlqehkhouyzjv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${PORT:8080}

app:
  jwt:
    secret: UHJvQ3JlZGl0b1NlY3JldEtleTIwMjZTdXBlclNlZ3VyYVBhcmFKV1RRdWVEZWJlU2VyTGFyZ2E=
    expiration-ms: 86400000

logging:
  level:
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR
    com.procredito.backend.security.JwtAuthenticationFilter: DEBUG
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
